# Generated by Django 4.2.4 on 2023-09-21 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_catimage_clan_interactinterestpoint_userdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catimage',
            old_name='image',
            new_name='image_uuid',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='image',
        ),
        migrations.AlterField(
            model_name='cat',
            name='lvl',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='catimage',
            name='cat_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.cat'),
        ),
        migrations.AlterField(
            model_name='catposition',
            name='cat_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='core.cat'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to=settings.AUTH_USER_MODEL),
        ),
    ]
