# Generated by Django 4.2.4 on 2023-09-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_image_catimage_image_uuid_remove_cat_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='clan',
            new_name='clan_id',
        ),
    ]
