# Generated by Django 4.2.4 on 2023-09-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_clan_userdata_clan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL),
        ),
    ]
