# Generated by Django 4.2.4 on 2023-09-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userdata_clan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_data', to='core.clan'),
        ),
    ]
