# Generated by Django 4.2.4 on 2023-11-24 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userdata_clan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='effect_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userdata',
            name='exp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userdata',
            name='limite_exp',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='userdata',
            name='lvl',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cat',
            name='lvl',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_uuid', models.UUIDField()),
                ('seed', models.IntegerField()),
                ('user_data_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='CatOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('cat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='core.cat')),
            ],
        ),
    ]
