# Generated by Django 4.2.4 on 2023-12-05 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clan_effect_id_userdata_exp_userdata_limite_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimage',
            name='image_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
